export enum WriteOffType {
  CARRIER_LOSS = 'CARRIER_LOSS',
  WAREHOUSE_LOSS = 'WAREHOUSE_LOSS',
  WAREHOUSE_THEFT = 'WAREHOUSE_THEFT',
  CARRIER_SHORTFALL = 'CARRIER_SHORTFALL',
  CONFISCATION = 'CONFISCATION',
  UTILIZATION = 'UTILIZATION'
}
